### ISSUE TITLE
113

### ISSUE THREAD

**Issue by centerionware** [james-things/bitsandbytes-prebuilt-all_arch#1]
Here's the first ever built with the cmakes that worked if want to list it for 113
[bitsandbytes_cuda113.zip](https://github.com/james-things/bitsandbytes-prebuilt-all_arch/files/10122789/bitsandbytes_cuda113.zip)

**Comment by james-things** [comment]
> Here's the first ever built with the cmakes that worked if want to list it for 113

Thank you for sharing this, and thank you especially much for sharing the cmakes. Going into this with no real cpp building experience I was struggling to work things out.

Can I ask what GPU hardware you compiled this on? The reason I built this dll was because the only other prebuilt version was throwing a kernel error for anyone running a Pascal series card, and that is what I currently have. After building it with the cmake scripts everything works properly; I had assumed that this was because the cmake script appears to target whatever architecture is found on the local machine, but correct me if that last bit is wrong.

It seems that the cuda version does not need to match exactly, as I built this on 116, but have received confirmation that it also runs on 113. So, with that said, knowing which architecture this dll was built on would be helpful. Especially if you have a different architecture, it might provide some good insights in testing!

**Comment by centerionware** [comment]
the  cmake scripts do compile it to run on any architecture (turing, pascal, etc etc), but it (the one i uploaded here of course) was built against cuda 113. It's very possible nvidia has kept their api stable and it could still work against other run time versions, but safest to compile against each different release just to be sure.
I did compile it on an RTX3080.
The line: 
```set_target_properties( bitsandbytes PROPERTIES CUDA_SEPARABLE_COMPILATION ON CUDA_ARCHITECTURES all)```
ensures it compiles shaders compatible with everything nvcc can compile for (that's pre-set in cmake) (it would(should maybe?) error at compile time if some architecture couldn't handle something)

**Comment by james-things** [comment]
> the cmake scripts...

Ah alright thank you for clarifying. I was aware of the way the original Makefile worked, but I hadn't used CMake before so I must have misinterpreted things. That makes a lot more sense! 

Out of curiousity, did you get the warning `CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. .minnctapersm will be ignored` spammed to console while compiling?

From my brief research I couldn't tell if this was a compiling on Windows issue or if it might be because I was compiling for higher architectures on a Pascal card. I have been in the midst of finals so I have had limited free time, unfortunately. Your dll works fine on my machine though, so if you did not get this warning then it would likely be the superior version! Curious to know. Thanks for your help! :)

**Comment by centerionware** [comment]
yeah I did get that warning. I just dug into it and cursory it seems __launch_bounds__() in kernel.ku (which is called many times) is what's causing the warning. 

Higher end archs support 2048 cuda threads, with lower ends (eg: rtx 2060) only going up to 1024 threads.
Basically the arguments passed are threadsPerBlock and Blocks, if it's passed 512,3* it's creating 512 threads, then 3 blocks of those threads, 512,3=1536 hence the warning. nvidia says nsight should be used to set the values by hand per arch for best results or something. :shrugs: As it _should_ just be "hand tuning" for performance, i'd think it should still work regardless of the warnings. Needs hard data to really know.
*Kernel.ku line 1576 for example


honestly I think the config I made is quite slow out of the box too, I did modify the cmake a bit locally in a different version that outputs a 71mb .dll to use -O3 with nvcc, link time optimization, and fast fp instead of precise , only tests I ran to test the difference was gpt-j-6b, the small .dll took ~396ms +- 10ms / token, and the 71mb dll dropped down to ~315 +- 15ms / token..  

```add_compile_definitions(BUILD_CUDA)
target_compile_options(bitsandbytes PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:
                       --generate-line-info
                       --use_fast_math
                       -O 3
                       >)
target_link_options(bitsandbytes PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:
						--use_fast_math
						-O 3
					   -lto
                       >)
IF (WIN32)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /fp:fast")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX2") #target_compile_options(bitsandbytes PRIVATE /arch:AVX2)
	set_property(TARGET bitsandbytes APPEND PROPERTY LINK_OPTIONS /OPT:NOREF) #Ensure it doesn't just toss out functions never called..
	target_link_libraries(bitsandbytes cudart cublas cublasLt curand cusparse pthreadVC3 )
ELSE()```

**Comment by james-things** [comment]
I am terribly sorry for not responding, things suddenly got busy back in December and I somehow missed your comment!

I appreciate the information though. I have not run into any issues using the compiled dll, so that would support your interpretation. I appreciate the additional build info as well - I will have to experiment a bit with fast fp. Thanks for the reply and apologies again for missing it!
